logging:
  #file:
  #name: log/lotte.log
  level:
    jdbc:
      connection: info
      resultsettable: info
      sqlonly: info
      sqltiming: info
    org:
      hibernate: info
      springframework:
        security: debug
    root: info
server:
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: a1s2d3F$
    url: jdbc:log4jdbc:mysql://43.200.181.70:3306/CodeBuddy
    username: codebuddy
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  resources:
    static-locations: file:/C:/Users/Java/Desktop/Workspace/LotteON2/files/

  jpa:
    database: mysql
    hibernate:
      #ddl-auto: update
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 591789449e2da1495d41e7af46686eb7
            client-secret: 5sQauVk5ojt0TcSFY06Gz2fpW7YUCLxa
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
    user:
      name: users
      password: 1234
  mail:
    host: smtp.gmail.com
    port: 465
    username: 'jeongminchoi1017@gmail.com'
    password: 'nrdvnfezqxejlgqx'
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.smtp.starttls.enable: true

  servlet:
    multipart:
      location: thumb/
      max-file-size: 10MB
upload:
  path:
    files: files/
    thumbs: src/main/frontend/public/thumbs/
    banners: banners/
    toppings: src/main/frontend/public/toppings/
    sides: src/main/frontend/public/sides/
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

app:
  version: 0.0.1-SNAPSHOT

